# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by backend/scripts/generate_models.py (Manually triggered)

from pydantic import BaseModel, Field
from typing import Optional

class AutoGeneratedParameters(BaseModel):
    # Application
    PN: str = Field(...)
    ST: str = Field(...)
    NOB: float = Field(..., ge=1, le=10)

    # Geometry
    H: float = Field(..., ge=0)
    LS: float = Field(...)
    W: float = Field(..., ge=0)
    L1: float = Field(..., ge=0)
    B: float = Field(..., ge=0)
    C: float = Field(..., ge=0)

    # Geometry (Optional)
    L2: Optional[float] = Field(None, ge=0)
    K: Optional[float] = Field(None, ge=0)
    N: Optional[float] = Field(None, ge=0)
    C2: Optional[float] = Field(None, ge=0)
    W1: Optional[float] = Field(None, ge=0)
    W2: Optional[float] = Field(None, ge=0)
    H1: Optional[float] = Field(None, ge=0)
    F: Optional[float] = Field(None, ge=0)
    G: Optional[float] = Field(None, ge=0)

    # Materials
    MX: str = Field(...)
    GREASE: str = Field(...)

    # Advanced
    SLL: Optional[str] = Field(None)
    CBB: Optional[float] = Field(None, ge=0)
    LL1: Optional[float] = Field(None, ge=0)
    CAA: Optional[float] = Field(None, ge=0)
    DD1DD2HH: Optional[str] = Field(None)
    ALT1: Optional[str] = Field(None)
    ALT2: Optional[str] = Field(None)
    ALT4: Optional[str] = Field(None)
